export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

interface IRootLayout{
  children : React.ReactNode
}

/*export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="it">
      <body>
        <main>{children}</main>
      </body>
    </html>
  )
}*/

export default function RootLayout(props : IRootLayout) {
  return (
    <html lang="it">
      <body>
        <main>{props.children}</main>
      </body>
    </html>
  )
}